.POSIX:
.SUFFIXES:
all:
	go build -o "morse-client"
install:
	cp morse-client /usr/local/bin
	cp morse-client.1 /usr/local/share/man/man1
uninstall:
	rm /usr/local/bin/morse-client
	rm /usr/local/share/man/man1/morse-client.1
